target("test_socket")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_socket.cpp")
    add_packages("mcpplibs-tinyhttps")

target("test_tls")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_tls.cpp")
    add_packages("mcpplibs-tinyhttps")

target("test_http")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_http.cpp")
    add_packages("mcpplibs-tinyhttps")

target("test_sse")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_sse.cpp")
    add_packages("mcpplibs-tinyhttps")

target("test_http_stream")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_http_stream.cpp")
    add_packages("mcpplibs-tinyhttps")

target("test_proxy")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_proxy.cpp")
    add_packages("mcpplibs-tinyhttps")

target("test_integration")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_integration.cpp")
    add_packages("mcpplibs-tinyhttps")
