target("test_socket")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_socket.cpp")
    add_deps("tinyhttps")

target("test_tls")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_tls.cpp")
    add_deps("tinyhttps")
