[package]
namespace   = "mcpplibs"
name        = "llmapi"
version     = "0.2.8"
description = "Modern C++ LLM API client with openai-compatible support"
license     = "Apache-2.0"
repo        = "https://github.com/mcpplibs/llmapi"

[build]
include_dirs = ["src/json"]

[targets.llmapi]
kind = "lib"

[dependencies.mcpplibs]
tinyhttps = "0.2.3"
