target("c_hello_mcpp")
    set_kind("binary")
    add_files("hello_mcpp.c")
    add_deps("llmapi_c")
    set_languages("c11")

target("c_basic")
    set_kind("binary")
    add_files("basic.c")
    add_deps("llmapi_c")
    set_languages("c11")

target("c_chat")
    set_kind("binary")
    add_files("chat.c")
    add_deps("llmapi_c")
    set_languages("c11")
