target("test_types")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_types.cpp")
    add_deps("llmapi")

target("test_serialization")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_serialization.cpp")
    add_deps("llmapi")

target("test_coro")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_coro.cpp")
    add_deps("llmapi")

target("test_client")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_client.cpp")
    add_deps("llmapi")

target("test_openai_serialize")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_openai_serialize.cpp")
    add_deps("llmapi")

target("test_anthropic_serialize")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_anthropic_serialize.cpp")
    add_deps("llmapi")

target("test_openai_live")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_openai_live.cpp")
    add_deps("llmapi")

target("test_anthropic_live")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_anthropic_live.cpp")
    add_deps("llmapi")

target("test_tool_calling")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_tool_calling.cpp")
    add_deps("llmapi")

target("test_structured_output")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_structured_output.cpp")
    add_deps("llmapi")

target("test_embeddings")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_embeddings.cpp")
    add_deps("llmapi")

target("test_llmapi_integration")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_llmapi_integration.cpp")
    add_deps("llmapi")
