target("test_types")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_types.cpp")
    add_deps("llmapi")

target("test_serialization")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_serialization.cpp")
    add_deps("llmapi")

target("test_coro")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_coro.cpp")
    add_deps("llmapi")

target("test_client")
    set_kind("binary")
    set_languages("c++23")
    set_policy("build.c++.modules", true)
    add_files("test_client.cpp")
    add_deps("llmapi")
